/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package students.Student;

import javax.swing.JOptionPane;

/**
 *
 * @author lts
 */
public class JDialogEditSut extends javax.swing.JDialog {

    private Student student;

    /**
     * Creates new form JDialogEditSut
     */
    public JDialogEditSut(java.awt.Frame parent, boolean modal, Student student) {
        super(parent, modal);
        initComponents();
        this.student = student;
        if (student.getId() > 0) {
            jButtonAdd.setEnabled(false);
            jButtonUpdate.setEnabled(true);
            jButtonDel.setEnabled(true);
            setStudentData(student);
        } else {
            jButtonAdd.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDel.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 6, 0));

        jButtonDel.setText("حذف");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDel);

        jButtonUpdate.setText("تعديل");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate);

        jButtonAdd.setText("اضافة");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        jLabel1.setText("المسلسل");
        jPanel2.add(jLabel1);

        jLabel3.setText("الاسم");
        jPanel2.add(jLabel3);

        jLabel4.setText("الكود");
        jPanel2.add(jLabel4);

        jLabel5.setText("العنوان");
        jPanel2.add(jLabel5);

        jLabel6.setText("رقم الهاتف");
        jPanel2.add(jLabel6);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        jLabelID.setText("0");
        jPanel3.add(jLabelID);

        jTextFieldName.setText("    ");
        jPanel3.add(jTextFieldName);
        jPanel3.add(jTextFieldCode);
        jPanel3.add(jTextFieldAddress);
        jPanel3.add(jTextFieldPhone);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel7.setText("ملاحظات");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if (checkStData() == true) {
            int insetStudent = new StudenDB().insetStudent(jTextFieldName.getText().trim(), jTextFieldCode.getText().trim(), jTextFieldAddress.getText().trim(), jTextFieldPhone.getText().trim(), jTextArea1.getText());
            if (insetStudent > 0) {
                JOptionPane.showMessageDialog(this, "تم اضافة الطالب بنجاح");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "حدث خطأ اثناء عملية الاضافة");

            }
        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        if (checkStData() == true) {
            int UpdateStudent = new StudenDB().UpdateStudent(getStudent().getId(), jTextFieldName.getText().trim(), jTextFieldCode.getText().trim(), jTextFieldAddress.getText().trim(), jTextFieldPhone.getText().trim(), jTextArea1.getText());
            if (UpdateStudent > 0) {
                JOptionPane.showMessageDialog(this, "تم تحديث البيانات بنجاح");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "حدث خطأ اثناء تحديث البيانات");
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        int delStudent = new StudenDB().delStudent(getStudent().getId());
        if(delStudent > 0){
        JOptionPane.showMessageDialog(this, "تم حذف الطالب بنجاح");
        this.dispose();
        }else{
        JOptionPane.showMessageDialog(this, "حدث خطأ اثناء عملية الحذف");
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEditSut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEditSut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEditSut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEditSut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEditSut dialog = new JDialogEditSut(new javax.swing.JFrame(), true, new Student());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables

    private boolean checkStData() {
        if (jTextFieldName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "الرجاء ادخال اسم الطالب");
        } else if (jTextFieldCode.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "الرجاء ادخال كود صحيح");
        } else if (jTextFieldPhone.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "الرجاء ادخال رقم الهاتف");
        } else if (jTextFieldAddress.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "الرجاء ادخال عنوان الطالب");
        } else {
            return true;
        }
        return false;
    }

    private void setStudentData(Student student) {
        jLabelID.setText("" + student.getId());
        jTextFieldName.setText(student.getName());
        jTextFieldAddress.setText(student.getAdress());
        jTextFieldCode.setText(student.getCode());
        jTextFieldPhone.setText(student.getPhone());
        jTextArea1.setText(student.getNots());

    }

    /**
     * @return the student
     */
    public Student getStudent() {
        return student;
    }

    /**
     * @param student the student to set
     */
    public void setStudent(Student student) {
        this.student = student;
    }
}
